// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/GameRule.proto

package com.kuaikai.game.common.msg.pb;

public final class GameRulePB {
  private GameRulePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code GameRule}
   */
  public enum GameRule
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>JIN_HUA = 99001;</code>
     *
     * <pre>
     * 扑克玩法：99开头
     * </pre>
     */
    JIN_HUA(0, 99001),
    /**
     * <code>NIU_NIU = 99002;</code>
     */
    NIU_NIU(1, 99002),
    /**
     * <code>BI_JI = 99003;</code>
     */
    BI_JI(2, 99003),
    /**
     * <code>WA_KENG = 99004;</code>
     */
    WA_KENG(3, 99004),
    /**
     * <code>TUI_DUI_ZI = 99005;</code>
     */
    TUI_DUI_ZI(4, 99005),
    /**
     * <code>ZHUO_LAO_MA_ZI = 99006;</code>
     */
    ZHUO_LAO_MA_ZI(5, 99006),
    /**
     * <code>SAN_DAI = 99007;</code>
     */
    SAN_DAI(6, 99007),
    /**
     * <code>GAN_DENG_YAN = 99008;</code>
     */
    GAN_DENG_YAN(7, 99008),
    /**
     * <code>DOU_DI_ZHU = 99009;</code>
     */
    DOU_DI_ZHU(8, 99009),
    ;

    /**
     * <code>JIN_HUA = 99001;</code>
     *
     * <pre>
     * 扑克玩法：99开头
     * </pre>
     */
    public static final int JIN_HUA_VALUE = 99001;
    /**
     * <code>NIU_NIU = 99002;</code>
     */
    public static final int NIU_NIU_VALUE = 99002;
    /**
     * <code>BI_JI = 99003;</code>
     */
    public static final int BI_JI_VALUE = 99003;
    /**
     * <code>WA_KENG = 99004;</code>
     */
    public static final int WA_KENG_VALUE = 99004;
    /**
     * <code>TUI_DUI_ZI = 99005;</code>
     */
    public static final int TUI_DUI_ZI_VALUE = 99005;
    /**
     * <code>ZHUO_LAO_MA_ZI = 99006;</code>
     */
    public static final int ZHUO_LAO_MA_ZI_VALUE = 99006;
    /**
     * <code>SAN_DAI = 99007;</code>
     */
    public static final int SAN_DAI_VALUE = 99007;
    /**
     * <code>GAN_DENG_YAN = 99008;</code>
     */
    public static final int GAN_DENG_YAN_VALUE = 99008;
    /**
     * <code>DOU_DI_ZHU = 99009;</code>
     */
    public static final int DOU_DI_ZHU_VALUE = 99009;


    public final int getNumber() { return value; }

    public static GameRule valueOf(int value) {
      switch (value) {
        case 99001: return JIN_HUA;
        case 99002: return NIU_NIU;
        case 99003: return BI_JI;
        case 99004: return WA_KENG;
        case 99005: return TUI_DUI_ZI;
        case 99006: return ZHUO_LAO_MA_ZI;
        case 99007: return SAN_DAI;
        case 99008: return GAN_DENG_YAN;
        case 99009: return DOU_DI_ZHU;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<GameRule>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameRule>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameRule>() {
            public GameRule findValueByNumber(int number) {
              return GameRule.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kuaikai.game.common.msg.pb.GameRulePB.getDescriptor().getEnumTypes().get(0);
    }

    private static final GameRule[] VALUES = values();

    public static GameRule valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private GameRule(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:GameRule)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025common/GameRule.proto*\241\001\n\010GameRule\022\r\n\007" +
      "JIN_HUA\020\271\205\006\022\r\n\007NIU_NIU\020\272\205\006\022\013\n\005BI_JI\020\273\205\006\022" +
      "\r\n\007WA_KENG\020\274\205\006\022\020\n\nTUI_DUI_ZI\020\275\205\006\022\024\n\016ZHUO" +
      "_LAO_MA_ZI\020\276\205\006\022\r\n\007SAN_DAI\020\277\205\006\022\022\n\014GAN_DEN" +
      "G_YAN\020\300\205\006\022\020\n\nDOU_DI_ZHU\020\301\205\006B,\n\036com.kuaik" +
      "ai.game.common.msg.pbB\nGameRulePB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
