// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/DeskInfo.proto

package com.kuaikai.game.common.msg.pb;

public final class DeskInfoPB {
  private DeskInfoPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DeskInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 deskId = 1;
    /**
     * <code>required int32 deskId = 1;</code>
     *
     * <pre>
     * 牌桌ID
     * </pre>
     */
    boolean hasDeskId();
    /**
     * <code>required int32 deskId = 1;</code>
     *
     * <pre>
     * 牌桌ID
     * </pre>
     */
    int getDeskId();

    // optional int32 clubId = 2;
    /**
     * <code>optional int32 clubId = 2;</code>
     *
     * <pre>
     * 俱乐部ID
     * </pre>
     */
    boolean hasClubId();
    /**
     * <code>optional int32 clubId = 2;</code>
     *
     * <pre>
     * 俱乐部ID
     * </pre>
     */
    int getClubId();

    // repeated .common.PlayerInfo players = 3;
    /**
     * <code>repeated .common.PlayerInfo players = 3;</code>
     *
     * <pre>
     * 所有玩家信息
     * </pre>
     */
    java.util.List<com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo> 
        getPlayersList();
    /**
     * <code>repeated .common.PlayerInfo players = 3;</code>
     *
     * <pre>
     * 所有玩家信息
     * </pre>
     */
    com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo getPlayers(int index);
    /**
     * <code>repeated .common.PlayerInfo players = 3;</code>
     *
     * <pre>
     * 所有玩家信息
     * </pre>
     */
    int getPlayersCount();
    /**
     * <code>repeated .common.PlayerInfo players = 3;</code>
     *
     * <pre>
     * 所有玩家信息
     * </pre>
     */
    java.util.List<? extends com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfoOrBuilder> 
        getPlayersOrBuilderList();
    /**
     * <code>repeated .common.PlayerInfo players = 3;</code>
     *
     * <pre>
     * 所有玩家信息
     * </pre>
     */
    com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfoOrBuilder getPlayersOrBuilder(
        int index);

    // optional .common.GameRule rule = 4;
    /**
     * <code>optional .common.GameRule rule = 4;</code>
     *
     * <pre>
     * 玩法编号
     * </pre>
     */
    boolean hasRule();
    /**
     * <code>optional .common.GameRule rule = 4;</code>
     *
     * <pre>
     * 玩法编号
     * </pre>
     */
    com.kuaikai.game.common.msg.pb.GameRulePB.GameRule getRule();

    // optional .common.GameSetting setting = 5;
    /**
     * <code>optional .common.GameSetting setting = 5;</code>
     *
     * <pre>
     * 规则设置
     * </pre>
     */
    boolean hasSetting();
    /**
     * <code>optional .common.GameSetting setting = 5;</code>
     *
     * <pre>
     * 规则设置
     * </pre>
     */
    com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting getSetting();
    /**
     * <code>optional .common.GameSetting setting = 5;</code>
     *
     * <pre>
     * 规则设置
     * </pre>
     */
    com.kuaikai.game.common.msg.pb.GameSettingPB.GameSettingOrBuilder getSettingOrBuilder();

    // optional .common.GameStatus status = 6;
    /**
     * <code>optional .common.GameStatus status = 6;</code>
     *
     * <pre>
     * 游戏状态
     * </pre>
     */
    boolean hasStatus();
    /**
     * <code>optional .common.GameStatus status = 6;</code>
     *
     * <pre>
     * 游戏状态
     * </pre>
     */
    com.kuaikai.game.common.msg.pb.GameStatusPB.GameStatus getStatus();
  }
  /**
   * Protobuf type {@code common.DeskInfo}
   *
   * <pre>
   * 牌桌信息
   * </pre>
   */
  public static final class DeskInfo extends
      com.google.protobuf.GeneratedMessage
      implements DeskInfoOrBuilder {
    // Use DeskInfo.newBuilder() to construct.
    private DeskInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeskInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeskInfo defaultInstance;
    public static DeskInfo getDefaultInstance() {
      return defaultInstance;
    }

    public DeskInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeskInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deskId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              clubId_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                players_ = new java.util.ArrayList<com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo>();
                mutable_bitField0_ |= 0x00000004;
              }
              players_.add(input.readMessage(com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo.PARSER, extensionRegistry));
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              com.kuaikai.game.common.msg.pb.GameRulePB.GameRule value = com.kuaikai.game.common.msg.pb.GameRulePB.GameRule.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                rule_ = value;
              }
              break;
            }
            case 42: {
              com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = setting_.toBuilder();
              }
              setting_ = input.readMessage(com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(setting_);
                setting_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.kuaikai.game.common.msg.pb.GameStatusPB.GameStatus value = com.kuaikai.game.common.msg.pb.GameStatusPB.GameStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                status_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          players_ = java.util.Collections.unmodifiableList(players_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kuaikai.game.common.msg.pb.DeskInfoPB.internal_static_common_DeskInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kuaikai.game.common.msg.pb.DeskInfoPB.internal_static_common_DeskInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.class, com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<DeskInfo> PARSER =
        new com.google.protobuf.AbstractParser<DeskInfo>() {
      public DeskInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeskInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeskInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 deskId = 1;
    public static final int DESKID_FIELD_NUMBER = 1;
    private int deskId_;
    /**
     * <code>required int32 deskId = 1;</code>
     *
     * <pre>
     * 牌桌ID
     * </pre>
     */
    public boolean hasDeskId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 deskId = 1;</code>
     *
     * <pre>
     * 牌桌ID
     * </pre>
     */
    public int getDeskId() {
      return deskId_;
    }

    // optional int32 clubId = 2;
    public static final int CLUBID_FIELD_NUMBER = 2;
    private int clubId_;
    /**
     * <code>optional int32 clubId = 2;</code>
     *
     * <pre>
     * 俱乐部ID
     * </pre>
     */
    public boolean hasClubId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 clubId = 2;</code>
     *
     * <pre>
     * 俱乐部ID
     * </pre>
     */
    public int getClubId() {
      return clubId_;
    }

    // repeated .common.PlayerInfo players = 3;
    public static final int PLAYERS_FIELD_NUMBER = 3;
    private java.util.List<com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo> players_;
    /**
     * <code>repeated .common.PlayerInfo players = 3;</code>
     *
     * <pre>
     * 所有玩家信息
     * </pre>
     */
    public java.util.List<com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo> getPlayersList() {
      return players_;
    }
    /**
     * <code>repeated .common.PlayerInfo players = 3;</code>
     *
     * <pre>
     * 所有玩家信息
     * </pre>
     */
    public java.util.List<? extends com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfoOrBuilder> 
        getPlayersOrBuilderList() {
      return players_;
    }
    /**
     * <code>repeated .common.PlayerInfo players = 3;</code>
     *
     * <pre>
     * 所有玩家信息
     * </pre>
     */
    public int getPlayersCount() {
      return players_.size();
    }
    /**
     * <code>repeated .common.PlayerInfo players = 3;</code>
     *
     * <pre>
     * 所有玩家信息
     * </pre>
     */
    public com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo getPlayers(int index) {
      return players_.get(index);
    }
    /**
     * <code>repeated .common.PlayerInfo players = 3;</code>
     *
     * <pre>
     * 所有玩家信息
     * </pre>
     */
    public com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfoOrBuilder getPlayersOrBuilder(
        int index) {
      return players_.get(index);
    }

    // optional .common.GameRule rule = 4;
    public static final int RULE_FIELD_NUMBER = 4;
    private com.kuaikai.game.common.msg.pb.GameRulePB.GameRule rule_;
    /**
     * <code>optional .common.GameRule rule = 4;</code>
     *
     * <pre>
     * 玩法编号
     * </pre>
     */
    public boolean hasRule() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .common.GameRule rule = 4;</code>
     *
     * <pre>
     * 玩法编号
     * </pre>
     */
    public com.kuaikai.game.common.msg.pb.GameRulePB.GameRule getRule() {
      return rule_;
    }

    // optional .common.GameSetting setting = 5;
    public static final int SETTING_FIELD_NUMBER = 5;
    private com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting setting_;
    /**
     * <code>optional .common.GameSetting setting = 5;</code>
     *
     * <pre>
     * 规则设置
     * </pre>
     */
    public boolean hasSetting() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .common.GameSetting setting = 5;</code>
     *
     * <pre>
     * 规则设置
     * </pre>
     */
    public com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting getSetting() {
      return setting_;
    }
    /**
     * <code>optional .common.GameSetting setting = 5;</code>
     *
     * <pre>
     * 规则设置
     * </pre>
     */
    public com.kuaikai.game.common.msg.pb.GameSettingPB.GameSettingOrBuilder getSettingOrBuilder() {
      return setting_;
    }

    // optional .common.GameStatus status = 6;
    public static final int STATUS_FIELD_NUMBER = 6;
    private com.kuaikai.game.common.msg.pb.GameStatusPB.GameStatus status_;
    /**
     * <code>optional .common.GameStatus status = 6;</code>
     *
     * <pre>
     * 游戏状态
     * </pre>
     */
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .common.GameStatus status = 6;</code>
     *
     * <pre>
     * 游戏状态
     * </pre>
     */
    public com.kuaikai.game.common.msg.pb.GameStatusPB.GameStatus getStatus() {
      return status_;
    }

    private void initFields() {
      deskId_ = 0;
      clubId_ = 0;
      players_ = java.util.Collections.emptyList();
      rule_ = com.kuaikai.game.common.msg.pb.GameRulePB.GameRule.JIN_HUA;
      setting_ = com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting.getDefaultInstance();
      status_ = com.kuaikai.game.common.msg.pb.GameStatusPB.GameStatus.WAITING;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDeskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPlayersCount(); i++) {
        if (!getPlayers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, deskId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, clubId_);
      }
      for (int i = 0; i < players_.size(); i++) {
        output.writeMessage(3, players_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(4, rule_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(5, setting_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(6, status_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, deskId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, clubId_);
      }
      for (int i = 0; i < players_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, players_.get(i));
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, rule_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, setting_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, status_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.DeskInfo}
     *
     * <pre>
     * 牌桌信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kuaikai.game.common.msg.pb.DeskInfoPB.internal_static_common_DeskInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kuaikai.game.common.msg.pb.DeskInfoPB.internal_static_common_DeskInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.class, com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.Builder.class);
      }

      // Construct using com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlayersFieldBuilder();
          getSettingFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deskId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        clubId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          playersBuilder_.clear();
        }
        rule_ = com.kuaikai.game.common.msg.pb.GameRulePB.GameRule.JIN_HUA;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (settingBuilder_ == null) {
          setting_ = com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting.getDefaultInstance();
        } else {
          settingBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        status_ = com.kuaikai.game.common.msg.pb.GameStatusPB.GameStatus.WAITING;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kuaikai.game.common.msg.pb.DeskInfoPB.internal_static_common_DeskInfo_descriptor;
      }

      public com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo getDefaultInstanceForType() {
        return com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.getDefaultInstance();
      }

      public com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo build() {
        com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo buildPartial() {
        com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo result = new com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deskId_ = deskId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clubId_ = clubId_;
        if (playersBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            players_ = java.util.Collections.unmodifiableList(players_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.players_ = players_;
        } else {
          result.players_ = playersBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rule_ = rule_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        if (settingBuilder_ == null) {
          result.setting_ = setting_;
        } else {
          result.setting_ = settingBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.status_ = status_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo) {
          return mergeFrom((com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo other) {
        if (other == com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.getDefaultInstance()) return this;
        if (other.hasDeskId()) {
          setDeskId(other.getDeskId());
        }
        if (other.hasClubId()) {
          setClubId(other.getClubId());
        }
        if (playersBuilder_ == null) {
          if (!other.players_.isEmpty()) {
            if (players_.isEmpty()) {
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePlayersIsMutable();
              players_.addAll(other.players_);
            }
            onChanged();
          }
        } else {
          if (!other.players_.isEmpty()) {
            if (playersBuilder_.isEmpty()) {
              playersBuilder_.dispose();
              playersBuilder_ = null;
              players_ = other.players_;
              bitField0_ = (bitField0_ & ~0x00000004);
              playersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPlayersFieldBuilder() : null;
            } else {
              playersBuilder_.addAllMessages(other.players_);
            }
          }
        }
        if (other.hasRule()) {
          setRule(other.getRule());
        }
        if (other.hasSetting()) {
          mergeSetting(other.getSetting());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeskId()) {
          
          return false;
        }
        for (int i = 0; i < getPlayersCount(); i++) {
          if (!getPlayers(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 deskId = 1;
      private int deskId_ ;
      /**
       * <code>required int32 deskId = 1;</code>
       *
       * <pre>
       * 牌桌ID
       * </pre>
       */
      public boolean hasDeskId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 deskId = 1;</code>
       *
       * <pre>
       * 牌桌ID
       * </pre>
       */
      public int getDeskId() {
        return deskId_;
      }
      /**
       * <code>required int32 deskId = 1;</code>
       *
       * <pre>
       * 牌桌ID
       * </pre>
       */
      public Builder setDeskId(int value) {
        bitField0_ |= 0x00000001;
        deskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 deskId = 1;</code>
       *
       * <pre>
       * 牌桌ID
       * </pre>
       */
      public Builder clearDeskId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deskId_ = 0;
        onChanged();
        return this;
      }

      // optional int32 clubId = 2;
      private int clubId_ ;
      /**
       * <code>optional int32 clubId = 2;</code>
       *
       * <pre>
       * 俱乐部ID
       * </pre>
       */
      public boolean hasClubId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 clubId = 2;</code>
       *
       * <pre>
       * 俱乐部ID
       * </pre>
       */
      public int getClubId() {
        return clubId_;
      }
      /**
       * <code>optional int32 clubId = 2;</code>
       *
       * <pre>
       * 俱乐部ID
       * </pre>
       */
      public Builder setClubId(int value) {
        bitField0_ |= 0x00000002;
        clubId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clubId = 2;</code>
       *
       * <pre>
       * 俱乐部ID
       * </pre>
       */
      public Builder clearClubId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clubId_ = 0;
        onChanged();
        return this;
      }

      // repeated .common.PlayerInfo players = 3;
      private java.util.List<com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo> players_ =
        java.util.Collections.emptyList();
      private void ensurePlayersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          players_ = new java.util.ArrayList<com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo>(players_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo, com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo.Builder, com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfoOrBuilder> playersBuilder_;

      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public java.util.List<com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo> getPlayersList() {
        if (playersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(players_);
        } else {
          return playersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public int getPlayersCount() {
        if (playersBuilder_ == null) {
          return players_.size();
        } else {
          return playersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo getPlayers(int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);
        } else {
          return playersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public Builder setPlayers(
          int index, com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.set(index, value);
          onChanged();
        } else {
          playersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public Builder setPlayers(
          int index, com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.set(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public Builder addPlayers(com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(value);
          onChanged();
        } else {
          playersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public Builder addPlayers(
          int index, com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo value) {
        if (playersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayersIsMutable();
          players_.add(index, value);
          onChanged();
        } else {
          playersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public Builder addPlayers(
          com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public Builder addPlayers(
          int index, com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo.Builder builderForValue) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.add(index, builderForValue.build());
          onChanged();
        } else {
          playersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public Builder addAllPlayers(
          java.lang.Iterable<? extends com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo> values) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          super.addAll(values, players_);
          onChanged();
        } else {
          playersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public Builder clearPlayers() {
        if (playersBuilder_ == null) {
          players_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          playersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public Builder removePlayers(int index) {
        if (playersBuilder_ == null) {
          ensurePlayersIsMutable();
          players_.remove(index);
          onChanged();
        } else {
          playersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo.Builder getPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfoOrBuilder getPlayersOrBuilder(
          int index) {
        if (playersBuilder_ == null) {
          return players_.get(index);  } else {
          return playersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public java.util.List<? extends com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfoOrBuilder> 
           getPlayersOrBuilderList() {
        if (playersBuilder_ != null) {
          return playersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(players_);
        }
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo.Builder addPlayersBuilder() {
        return getPlayersFieldBuilder().addBuilder(
            com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo.Builder addPlayersBuilder(
          int index) {
        return getPlayersFieldBuilder().addBuilder(
            index, com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .common.PlayerInfo players = 3;</code>
       *
       * <pre>
       * 所有玩家信息
       * </pre>
       */
      public java.util.List<com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo.Builder> 
           getPlayersBuilderList() {
        return getPlayersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo, com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo.Builder, com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfoOrBuilder> 
          getPlayersFieldBuilder() {
        if (playersBuilder_ == null) {
          playersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo, com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfo.Builder, com.kuaikai.game.common.msg.pb.PlayerInfoPB.PlayerInfoOrBuilder>(
                  players_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          players_ = null;
        }
        return playersBuilder_;
      }

      // optional .common.GameRule rule = 4;
      private com.kuaikai.game.common.msg.pb.GameRulePB.GameRule rule_ = com.kuaikai.game.common.msg.pb.GameRulePB.GameRule.JIN_HUA;
      /**
       * <code>optional .common.GameRule rule = 4;</code>
       *
       * <pre>
       * 玩法编号
       * </pre>
       */
      public boolean hasRule() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .common.GameRule rule = 4;</code>
       *
       * <pre>
       * 玩法编号
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.GameRulePB.GameRule getRule() {
        return rule_;
      }
      /**
       * <code>optional .common.GameRule rule = 4;</code>
       *
       * <pre>
       * 玩法编号
       * </pre>
       */
      public Builder setRule(com.kuaikai.game.common.msg.pb.GameRulePB.GameRule value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        rule_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .common.GameRule rule = 4;</code>
       *
       * <pre>
       * 玩法编号
       * </pre>
       */
      public Builder clearRule() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rule_ = com.kuaikai.game.common.msg.pb.GameRulePB.GameRule.JIN_HUA;
        onChanged();
        return this;
      }

      // optional .common.GameSetting setting = 5;
      private com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting setting_ = com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting, com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting.Builder, com.kuaikai.game.common.msg.pb.GameSettingPB.GameSettingOrBuilder> settingBuilder_;
      /**
       * <code>optional .common.GameSetting setting = 5;</code>
       *
       * <pre>
       * 规则设置
       * </pre>
       */
      public boolean hasSetting() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .common.GameSetting setting = 5;</code>
       *
       * <pre>
       * 规则设置
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting getSetting() {
        if (settingBuilder_ == null) {
          return setting_;
        } else {
          return settingBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .common.GameSetting setting = 5;</code>
       *
       * <pre>
       * 规则设置
       * </pre>
       */
      public Builder setSetting(com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting value) {
        if (settingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          setting_ = value;
          onChanged();
        } else {
          settingBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .common.GameSetting setting = 5;</code>
       *
       * <pre>
       * 规则设置
       * </pre>
       */
      public Builder setSetting(
          com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting.Builder builderForValue) {
        if (settingBuilder_ == null) {
          setting_ = builderForValue.build();
          onChanged();
        } else {
          settingBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .common.GameSetting setting = 5;</code>
       *
       * <pre>
       * 规则设置
       * </pre>
       */
      public Builder mergeSetting(com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting value) {
        if (settingBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              setting_ != com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting.getDefaultInstance()) {
            setting_ =
              com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting.newBuilder(setting_).mergeFrom(value).buildPartial();
          } else {
            setting_ = value;
          }
          onChanged();
        } else {
          settingBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .common.GameSetting setting = 5;</code>
       *
       * <pre>
       * 规则设置
       * </pre>
       */
      public Builder clearSetting() {
        if (settingBuilder_ == null) {
          setting_ = com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting.getDefaultInstance();
          onChanged();
        } else {
          settingBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .common.GameSetting setting = 5;</code>
       *
       * <pre>
       * 规则设置
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting.Builder getSettingBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getSettingFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .common.GameSetting setting = 5;</code>
       *
       * <pre>
       * 规则设置
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.GameSettingPB.GameSettingOrBuilder getSettingOrBuilder() {
        if (settingBuilder_ != null) {
          return settingBuilder_.getMessageOrBuilder();
        } else {
          return setting_;
        }
      }
      /**
       * <code>optional .common.GameSetting setting = 5;</code>
       *
       * <pre>
       * 规则设置
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting, com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting.Builder, com.kuaikai.game.common.msg.pb.GameSettingPB.GameSettingOrBuilder> 
          getSettingFieldBuilder() {
        if (settingBuilder_ == null) {
          settingBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting, com.kuaikai.game.common.msg.pb.GameSettingPB.GameSetting.Builder, com.kuaikai.game.common.msg.pb.GameSettingPB.GameSettingOrBuilder>(
                  setting_,
                  getParentForChildren(),
                  isClean());
          setting_ = null;
        }
        return settingBuilder_;
      }

      // optional .common.GameStatus status = 6;
      private com.kuaikai.game.common.msg.pb.GameStatusPB.GameStatus status_ = com.kuaikai.game.common.msg.pb.GameStatusPB.GameStatus.WAITING;
      /**
       * <code>optional .common.GameStatus status = 6;</code>
       *
       * <pre>
       * 游戏状态
       * </pre>
       */
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .common.GameStatus status = 6;</code>
       *
       * <pre>
       * 游戏状态
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.GameStatusPB.GameStatus getStatus() {
        return status_;
      }
      /**
       * <code>optional .common.GameStatus status = 6;</code>
       *
       * <pre>
       * 游戏状态
       * </pre>
       */
      public Builder setStatus(com.kuaikai.game.common.msg.pb.GameStatusPB.GameStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .common.GameStatus status = 6;</code>
       *
       * <pre>
       * 游戏状态
       * </pre>
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000020);
        status_ = com.kuaikai.game.common.msg.pb.GameStatusPB.GameStatus.WAITING;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:common.DeskInfo)
    }

    static {
      defaultInstance = new DeskInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common.DeskInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_DeskInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_DeskInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025common/DeskInfo.proto\022\006common\032\027common/" +
      "PlayerInfo.proto\032\030common/GameSetting.pro" +
      "to\032\025common/GameRule.proto\032\027common/GameSt" +
      "atus.proto\"\271\001\n\010DeskInfo\022\016\n\006deskId\030\001 \002(\005\022" +
      "\016\n\006clubId\030\002 \001(\005\022#\n\007players\030\003 \003(\0132\022.commo" +
      "n.PlayerInfo\022\036\n\004rule\030\004 \001(\0162\020.common.Game" +
      "Rule\022$\n\007setting\030\005 \001(\0132\023.common.GameSetti" +
      "ng\022\"\n\006status\030\006 \001(\0162\022.common.GameStatusB," +
      "\n\036com.kuaikai.game.common.msg.pbB\nDeskIn" +
      "foPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_common_DeskInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_common_DeskInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_common_DeskInfo_descriptor,
              new java.lang.String[] { "DeskId", "ClubId", "Players", "Rule", "Setting", "Status", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kuaikai.game.common.msg.pb.PlayerInfoPB.getDescriptor(),
          com.kuaikai.game.common.msg.pb.GameSettingPB.getDescriptor(),
          com.kuaikai.game.common.msg.pb.GameRulePB.getDescriptor(),
          com.kuaikai.game.common.msg.pb.GameStatusPB.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
