// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/MahjongTheme.proto

package com.kuaikai.game.common.msg.pb;

public final class MahjongThemePB {
  private MahjongThemePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code common.MahjongTheme}
   *
   * <pre>
   * 配色方案
   * </pre>
   */
  public enum MahjongTheme
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GREEN = 1;</code>
     */
    GREEN(0, 1),
    /**
     * <code>YELLOW = 2;</code>
     */
    YELLOW(1, 2),
    /**
     * <code>BLUE = 3;</code>
     */
    BLUE(2, 3),
    ;

    /**
     * <code>GREEN = 1;</code>
     */
    public static final int GREEN_VALUE = 1;
    /**
     * <code>YELLOW = 2;</code>
     */
    public static final int YELLOW_VALUE = 2;
    /**
     * <code>BLUE = 3;</code>
     */
    public static final int BLUE_VALUE = 3;


    public final int getNumber() { return value; }

    public static MahjongTheme valueOf(int value) {
      switch (value) {
        case 1: return GREEN;
        case 2: return YELLOW;
        case 3: return BLUE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MahjongTheme>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MahjongTheme>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MahjongTheme>() {
            public MahjongTheme findValueByNumber(int number) {
              return MahjongTheme.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.kuaikai.game.common.msg.pb.MahjongThemePB.getDescriptor().getEnumTypes().get(0);
    }

    private static final MahjongTheme[] VALUES = values();

    public static MahjongTheme valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MahjongTheme(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:common.MahjongTheme)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031common/MahjongTheme.proto\022\006common*/\n\014M" +
      "ahjongTheme\022\t\n\005GREEN\020\001\022\n\n\006YELLOW\020\002\022\010\n\004BL" +
      "UE\020\003B0\n\036com.kuaikai.game.common.msg.pbB\016" +
      "MahjongThemePB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
