// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mahjong/CBet.proto

package com.kuaikai.game.mahjong.msg.pb;

public final class CBetPB {
  private CBetPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CBetOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 bet = 1;
    /**
     * <code>required int32 bet = 1;</code>
     *
     * <pre>
     * 下注数
     * </pre>
     */
    boolean hasBet();
    /**
     * <code>required int32 bet = 1;</code>
     *
     * <pre>
     * 下注数
     * </pre>
     */
    int getBet();
  }
  /**
   * Protobuf type {@code mahjong.CBet}
   *
   * <pre>
   * 玩家请求下注
   * </pre>
   */
  public static final class CBet extends
      com.google.protobuf.GeneratedMessage
      implements CBetOrBuilder {
    // Use CBet.newBuilder() to construct.
    private CBet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CBet(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CBet defaultInstance;
    public static CBet getDefaultInstance() {
      return defaultInstance;
    }

    public CBet getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CBet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              bet_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kuaikai.game.mahjong.msg.pb.CBetPB.internal_static_mahjong_CBet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kuaikai.game.mahjong.msg.pb.CBetPB.internal_static_mahjong_CBet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet.class, com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet.Builder.class);
    }

    public static com.google.protobuf.Parser<CBet> PARSER =
        new com.google.protobuf.AbstractParser<CBet>() {
      public CBet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CBet(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CBet> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 bet = 1;
    public static final int BET_FIELD_NUMBER = 1;
    private int bet_;
    /**
     * <code>required int32 bet = 1;</code>
     *
     * <pre>
     * 下注数
     * </pre>
     */
    public boolean hasBet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 bet = 1;</code>
     *
     * <pre>
     * 下注数
     * </pre>
     */
    public int getBet() {
      return bet_;
    }

    private void initFields() {
      bet_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBet()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, bet_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, bet_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mahjong.CBet}
     *
     * <pre>
     * 玩家请求下注
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kuaikai.game.mahjong.msg.pb.CBetPB.CBetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kuaikai.game.mahjong.msg.pb.CBetPB.internal_static_mahjong_CBet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kuaikai.game.mahjong.msg.pb.CBetPB.internal_static_mahjong_CBet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet.class, com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet.Builder.class);
      }

      // Construct using com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        bet_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kuaikai.game.mahjong.msg.pb.CBetPB.internal_static_mahjong_CBet_descriptor;
      }

      public com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet getDefaultInstanceForType() {
        return com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet.getDefaultInstance();
      }

      public com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet build() {
        com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet buildPartial() {
        com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet result = new com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bet_ = bet_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet) {
          return mergeFrom((com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet other) {
        if (other == com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet.getDefaultInstance()) return this;
        if (other.hasBet()) {
          setBet(other.getBet());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBet()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kuaikai.game.mahjong.msg.pb.CBetPB.CBet) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 bet = 1;
      private int bet_ ;
      /**
       * <code>required int32 bet = 1;</code>
       *
       * <pre>
       * 下注数
       * </pre>
       */
      public boolean hasBet() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 bet = 1;</code>
       *
       * <pre>
       * 下注数
       * </pre>
       */
      public int getBet() {
        return bet_;
      }
      /**
       * <code>required int32 bet = 1;</code>
       *
       * <pre>
       * 下注数
       * </pre>
       */
      public Builder setBet(int value) {
        bitField0_ |= 0x00000001;
        bet_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 bet = 1;</code>
       *
       * <pre>
       * 下注数
       * </pre>
       */
      public Builder clearBet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        bet_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mahjong.CBet)
    }

    static {
      defaultInstance = new CBet(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mahjong.CBet)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mahjong_CBet_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mahjong_CBet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022mahjong/CBet.proto\022\007mahjong\"\023\n\004CBet\022\013\n" +
      "\003bet\030\001 \002(\005B)\n\037com.kuaikai.game.mahjong.m" +
      "sg.pbB\006CBetPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mahjong_CBet_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mahjong_CBet_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mahjong_CBet_descriptor,
              new java.lang.String[] { "Bet", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
