// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mahjong/SGameResult.proto

package com.kuaikai.game.mahjong.msg.pb;

public final class SGameResultPB {
  private SGameResultPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SGameResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .mahjong.PlayerGameResult playerGameResults = 1;
    /**
     * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
     *
     * <pre>
     * 所有玩家整场牌局结算
     * </pre>
     */
    java.util.List<com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult> 
        getPlayerGameResultsList();
    /**
     * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
     *
     * <pre>
     * 所有玩家整场牌局结算
     * </pre>
     */
    com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult getPlayerGameResults(int index);
    /**
     * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
     *
     * <pre>
     * 所有玩家整场牌局结算
     * </pre>
     */
    int getPlayerGameResultsCount();
    /**
     * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
     *
     * <pre>
     * 所有玩家整场牌局结算
     * </pre>
     */
    java.util.List<? extends com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResultOrBuilder> 
        getPlayerGameResultsOrBuilderList();
    /**
     * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
     *
     * <pre>
     * 所有玩家整场牌局结算
     * </pre>
     */
    com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResultOrBuilder getPlayerGameResultsOrBuilder(
        int index);

    // optional int32 finalSet = 2;
    /**
     * <code>optional int32 finalSet = 2;</code>
     *
     * <pre>
     * 结束时局数
     * </pre>
     */
    boolean hasFinalSet();
    /**
     * <code>optional int32 finalSet = 2;</code>
     *
     * <pre>
     * 结束时局数
     * </pre>
     */
    int getFinalSet();

    // optional int64 endTime = 3;
    /**
     * <code>optional int64 endTime = 3;</code>
     *
     * <pre>
     * 结束时间
     * </pre>
     */
    boolean hasEndTime();
    /**
     * <code>optional int64 endTime = 3;</code>
     *
     * <pre>
     * 结束时间
     * </pre>
     */
    long getEndTime();

    // optional bool dismiss = 4;
    /**
     * <code>optional bool dismiss = 4;</code>
     *
     * <pre>
     * 是否解散
     * </pre>
     */
    boolean hasDismiss();
    /**
     * <code>optional bool dismiss = 4;</code>
     *
     * <pre>
     * 是否解散
     * </pre>
     */
    boolean getDismiss();
  }
  /**
   * Protobuf type {@code mahjong.SGameResult}
   *
   * <pre>
   * 返回整场牌局结果
   * </pre>
   */
  public static final class SGameResult extends
      com.google.protobuf.GeneratedMessage
      implements SGameResultOrBuilder {
    // Use SGameResult.newBuilder() to construct.
    private SGameResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SGameResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SGameResult defaultInstance;
    public static SGameResult getDefaultInstance() {
      return defaultInstance;
    }

    public SGameResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SGameResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                playerGameResults_ = new java.util.ArrayList<com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult>();
                mutable_bitField0_ |= 0x00000001;
              }
              playerGameResults_.add(input.readMessage(com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult.PARSER, extensionRegistry));
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              finalSet_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              endTime_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              dismiss_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          playerGameResults_ = java.util.Collections.unmodifiableList(playerGameResults_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kuaikai.game.mahjong.msg.pb.SGameResultPB.internal_static_mahjong_SGameResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kuaikai.game.mahjong.msg.pb.SGameResultPB.internal_static_mahjong_SGameResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult.class, com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult.Builder.class);
    }

    public static com.google.protobuf.Parser<SGameResult> PARSER =
        new com.google.protobuf.AbstractParser<SGameResult>() {
      public SGameResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SGameResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SGameResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated .mahjong.PlayerGameResult playerGameResults = 1;
    public static final int PLAYERGAMERESULTS_FIELD_NUMBER = 1;
    private java.util.List<com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult> playerGameResults_;
    /**
     * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
     *
     * <pre>
     * 所有玩家整场牌局结算
     * </pre>
     */
    public java.util.List<com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult> getPlayerGameResultsList() {
      return playerGameResults_;
    }
    /**
     * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
     *
     * <pre>
     * 所有玩家整场牌局结算
     * </pre>
     */
    public java.util.List<? extends com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResultOrBuilder> 
        getPlayerGameResultsOrBuilderList() {
      return playerGameResults_;
    }
    /**
     * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
     *
     * <pre>
     * 所有玩家整场牌局结算
     * </pre>
     */
    public int getPlayerGameResultsCount() {
      return playerGameResults_.size();
    }
    /**
     * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
     *
     * <pre>
     * 所有玩家整场牌局结算
     * </pre>
     */
    public com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult getPlayerGameResults(int index) {
      return playerGameResults_.get(index);
    }
    /**
     * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
     *
     * <pre>
     * 所有玩家整场牌局结算
     * </pre>
     */
    public com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResultOrBuilder getPlayerGameResultsOrBuilder(
        int index) {
      return playerGameResults_.get(index);
    }

    // optional int32 finalSet = 2;
    public static final int FINALSET_FIELD_NUMBER = 2;
    private int finalSet_;
    /**
     * <code>optional int32 finalSet = 2;</code>
     *
     * <pre>
     * 结束时局数
     * </pre>
     */
    public boolean hasFinalSet() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 finalSet = 2;</code>
     *
     * <pre>
     * 结束时局数
     * </pre>
     */
    public int getFinalSet() {
      return finalSet_;
    }

    // optional int64 endTime = 3;
    public static final int ENDTIME_FIELD_NUMBER = 3;
    private long endTime_;
    /**
     * <code>optional int64 endTime = 3;</code>
     *
     * <pre>
     * 结束时间
     * </pre>
     */
    public boolean hasEndTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 endTime = 3;</code>
     *
     * <pre>
     * 结束时间
     * </pre>
     */
    public long getEndTime() {
      return endTime_;
    }

    // optional bool dismiss = 4;
    public static final int DISMISS_FIELD_NUMBER = 4;
    private boolean dismiss_;
    /**
     * <code>optional bool dismiss = 4;</code>
     *
     * <pre>
     * 是否解散
     * </pre>
     */
    public boolean hasDismiss() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool dismiss = 4;</code>
     *
     * <pre>
     * 是否解散
     * </pre>
     */
    public boolean getDismiss() {
      return dismiss_;
    }

    private void initFields() {
      playerGameResults_ = java.util.Collections.emptyList();
      finalSet_ = 0;
      endTime_ = 0L;
      dismiss_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getPlayerGameResultsCount(); i++) {
        if (!getPlayerGameResults(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < playerGameResults_.size(); i++) {
        output.writeMessage(1, playerGameResults_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, finalSet_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(3, endTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(4, dismiss_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < playerGameResults_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, playerGameResults_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, finalSet_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, endTime_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, dismiss_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mahjong.SGameResult}
     *
     * <pre>
     * 返回整场牌局结果
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kuaikai.game.mahjong.msg.pb.SGameResultPB.internal_static_mahjong_SGameResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kuaikai.game.mahjong.msg.pb.SGameResultPB.internal_static_mahjong_SGameResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult.class, com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult.Builder.class);
      }

      // Construct using com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPlayerGameResultsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (playerGameResultsBuilder_ == null) {
          playerGameResults_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          playerGameResultsBuilder_.clear();
        }
        finalSet_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        endTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        dismiss_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kuaikai.game.mahjong.msg.pb.SGameResultPB.internal_static_mahjong_SGameResult_descriptor;
      }

      public com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult getDefaultInstanceForType() {
        return com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult.getDefaultInstance();
      }

      public com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult build() {
        com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult buildPartial() {
        com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult result = new com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (playerGameResultsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            playerGameResults_ = java.util.Collections.unmodifiableList(playerGameResults_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.playerGameResults_ = playerGameResults_;
        } else {
          result.playerGameResults_ = playerGameResultsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.finalSet_ = finalSet_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.endTime_ = endTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dismiss_ = dismiss_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult) {
          return mergeFrom((com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult other) {
        if (other == com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult.getDefaultInstance()) return this;
        if (playerGameResultsBuilder_ == null) {
          if (!other.playerGameResults_.isEmpty()) {
            if (playerGameResults_.isEmpty()) {
              playerGameResults_ = other.playerGameResults_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePlayerGameResultsIsMutable();
              playerGameResults_.addAll(other.playerGameResults_);
            }
            onChanged();
          }
        } else {
          if (!other.playerGameResults_.isEmpty()) {
            if (playerGameResultsBuilder_.isEmpty()) {
              playerGameResultsBuilder_.dispose();
              playerGameResultsBuilder_ = null;
              playerGameResults_ = other.playerGameResults_;
              bitField0_ = (bitField0_ & ~0x00000001);
              playerGameResultsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPlayerGameResultsFieldBuilder() : null;
            } else {
              playerGameResultsBuilder_.addAllMessages(other.playerGameResults_);
            }
          }
        }
        if (other.hasFinalSet()) {
          setFinalSet(other.getFinalSet());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasDismiss()) {
          setDismiss(other.getDismiss());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPlayerGameResultsCount(); i++) {
          if (!getPlayerGameResults(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kuaikai.game.mahjong.msg.pb.SGameResultPB.SGameResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .mahjong.PlayerGameResult playerGameResults = 1;
      private java.util.List<com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult> playerGameResults_ =
        java.util.Collections.emptyList();
      private void ensurePlayerGameResultsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          playerGameResults_ = new java.util.ArrayList<com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult>(playerGameResults_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult, com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult.Builder, com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResultOrBuilder> playerGameResultsBuilder_;

      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public java.util.List<com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult> getPlayerGameResultsList() {
        if (playerGameResultsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(playerGameResults_);
        } else {
          return playerGameResultsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public int getPlayerGameResultsCount() {
        if (playerGameResultsBuilder_ == null) {
          return playerGameResults_.size();
        } else {
          return playerGameResultsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult getPlayerGameResults(int index) {
        if (playerGameResultsBuilder_ == null) {
          return playerGameResults_.get(index);
        } else {
          return playerGameResultsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public Builder setPlayerGameResults(
          int index, com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult value) {
        if (playerGameResultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerGameResultsIsMutable();
          playerGameResults_.set(index, value);
          onChanged();
        } else {
          playerGameResultsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public Builder setPlayerGameResults(
          int index, com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult.Builder builderForValue) {
        if (playerGameResultsBuilder_ == null) {
          ensurePlayerGameResultsIsMutable();
          playerGameResults_.set(index, builderForValue.build());
          onChanged();
        } else {
          playerGameResultsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public Builder addPlayerGameResults(com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult value) {
        if (playerGameResultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerGameResultsIsMutable();
          playerGameResults_.add(value);
          onChanged();
        } else {
          playerGameResultsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public Builder addPlayerGameResults(
          int index, com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult value) {
        if (playerGameResultsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePlayerGameResultsIsMutable();
          playerGameResults_.add(index, value);
          onChanged();
        } else {
          playerGameResultsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public Builder addPlayerGameResults(
          com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult.Builder builderForValue) {
        if (playerGameResultsBuilder_ == null) {
          ensurePlayerGameResultsIsMutable();
          playerGameResults_.add(builderForValue.build());
          onChanged();
        } else {
          playerGameResultsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public Builder addPlayerGameResults(
          int index, com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult.Builder builderForValue) {
        if (playerGameResultsBuilder_ == null) {
          ensurePlayerGameResultsIsMutable();
          playerGameResults_.add(index, builderForValue.build());
          onChanged();
        } else {
          playerGameResultsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public Builder addAllPlayerGameResults(
          java.lang.Iterable<? extends com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult> values) {
        if (playerGameResultsBuilder_ == null) {
          ensurePlayerGameResultsIsMutable();
          super.addAll(values, playerGameResults_);
          onChanged();
        } else {
          playerGameResultsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public Builder clearPlayerGameResults() {
        if (playerGameResultsBuilder_ == null) {
          playerGameResults_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          playerGameResultsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public Builder removePlayerGameResults(int index) {
        if (playerGameResultsBuilder_ == null) {
          ensurePlayerGameResultsIsMutable();
          playerGameResults_.remove(index);
          onChanged();
        } else {
          playerGameResultsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult.Builder getPlayerGameResultsBuilder(
          int index) {
        return getPlayerGameResultsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResultOrBuilder getPlayerGameResultsOrBuilder(
          int index) {
        if (playerGameResultsBuilder_ == null) {
          return playerGameResults_.get(index);  } else {
          return playerGameResultsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public java.util.List<? extends com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResultOrBuilder> 
           getPlayerGameResultsOrBuilderList() {
        if (playerGameResultsBuilder_ != null) {
          return playerGameResultsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(playerGameResults_);
        }
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult.Builder addPlayerGameResultsBuilder() {
        return getPlayerGameResultsFieldBuilder().addBuilder(
            com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult.getDefaultInstance());
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult.Builder addPlayerGameResultsBuilder(
          int index) {
        return getPlayerGameResultsFieldBuilder().addBuilder(
            index, com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult.getDefaultInstance());
      }
      /**
       * <code>repeated .mahjong.PlayerGameResult playerGameResults = 1;</code>
       *
       * <pre>
       * 所有玩家整场牌局结算
       * </pre>
       */
      public java.util.List<com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult.Builder> 
           getPlayerGameResultsBuilderList() {
        return getPlayerGameResultsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult, com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult.Builder, com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResultOrBuilder> 
          getPlayerGameResultsFieldBuilder() {
        if (playerGameResultsBuilder_ == null) {
          playerGameResultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult, com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResult.Builder, com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.PlayerGameResultOrBuilder>(
                  playerGameResults_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          playerGameResults_ = null;
        }
        return playerGameResultsBuilder_;
      }

      // optional int32 finalSet = 2;
      private int finalSet_ ;
      /**
       * <code>optional int32 finalSet = 2;</code>
       *
       * <pre>
       * 结束时局数
       * </pre>
       */
      public boolean hasFinalSet() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 finalSet = 2;</code>
       *
       * <pre>
       * 结束时局数
       * </pre>
       */
      public int getFinalSet() {
        return finalSet_;
      }
      /**
       * <code>optional int32 finalSet = 2;</code>
       *
       * <pre>
       * 结束时局数
       * </pre>
       */
      public Builder setFinalSet(int value) {
        bitField0_ |= 0x00000002;
        finalSet_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 finalSet = 2;</code>
       *
       * <pre>
       * 结束时局数
       * </pre>
       */
      public Builder clearFinalSet() {
        bitField0_ = (bitField0_ & ~0x00000002);
        finalSet_ = 0;
        onChanged();
        return this;
      }

      // optional int64 endTime = 3;
      private long endTime_ ;
      /**
       * <code>optional int64 endTime = 3;</code>
       *
       * <pre>
       * 结束时间
       * </pre>
       */
      public boolean hasEndTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 endTime = 3;</code>
       *
       * <pre>
       * 结束时间
       * </pre>
       */
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>optional int64 endTime = 3;</code>
       *
       * <pre>
       * 结束时间
       * </pre>
       */
      public Builder setEndTime(long value) {
        bitField0_ |= 0x00000004;
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 endTime = 3;</code>
       *
       * <pre>
       * 结束时间
       * </pre>
       */
      public Builder clearEndTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endTime_ = 0L;
        onChanged();
        return this;
      }

      // optional bool dismiss = 4;
      private boolean dismiss_ ;
      /**
       * <code>optional bool dismiss = 4;</code>
       *
       * <pre>
       * 是否解散
       * </pre>
       */
      public boolean hasDismiss() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool dismiss = 4;</code>
       *
       * <pre>
       * 是否解散
       * </pre>
       */
      public boolean getDismiss() {
        return dismiss_;
      }
      /**
       * <code>optional bool dismiss = 4;</code>
       *
       * <pre>
       * 是否解散
       * </pre>
       */
      public Builder setDismiss(boolean value) {
        bitField0_ |= 0x00000008;
        dismiss_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool dismiss = 4;</code>
       *
       * <pre>
       * 是否解散
       * </pre>
       */
      public Builder clearDismiss() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dismiss_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:mahjong.SGameResult)
    }

    static {
      defaultInstance = new SGameResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:mahjong.SGameResult)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_mahjong_SGameResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_mahjong_SGameResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031mahjong/SGameResult.proto\022\007mahjong\032\036ma" +
      "hjong/PlayerGameResult.proto\"w\n\013SGameRes" +
      "ult\0224\n\021playerGameResults\030\001 \003(\0132\031.mahjong" +
      ".PlayerGameResult\022\020\n\010finalSet\030\002 \001(\005\022\017\n\007e" +
      "ndTime\030\003 \001(\003\022\017\n\007dismiss\030\004 \001(\010B0\n\037com.kua" +
      "ikai.game.mahjong.msg.pbB\rSGameResultPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_mahjong_SGameResult_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_mahjong_SGameResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_mahjong_SGameResult_descriptor,
              new java.lang.String[] { "PlayerGameResults", "FinalSet", "EndTime", "Dismiss", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kuaikai.game.mahjong.msg.pb.PlayerGameResultPB.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
