// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/DeskUniq.proto

package com.kuaikai.game.common.msg.pb;

public final class DeskUniqPB {
  private DeskUniqPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DeskUniqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 deskId = 1;
    /**
     * <code>required int64 deskId = 1;</code>
     */
    boolean hasDeskId();
    /**
     * <code>required int64 deskId = 1;</code>
     */
    long getDeskId();

    // optional int32 clubId = 2;
    /**
     * <code>optional int32 clubId = 2;</code>
     */
    boolean hasClubId();
    /**
     * <code>optional int32 clubId = 2;</code>
     */
    int getClubId();
  }
  /**
   * Protobuf type {@code common.DeskUniq}
   *
   * <pre>
   * 牌桌唯一标识
   * </pre>
   */
  public static final class DeskUniq extends
      com.google.protobuf.GeneratedMessage
      implements DeskUniqOrBuilder {
    // Use DeskUniq.newBuilder() to construct.
    private DeskUniq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeskUniq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeskUniq defaultInstance;
    public static DeskUniq getDefaultInstance() {
      return defaultInstance;
    }

    public DeskUniq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeskUniq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deskId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              clubId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kuaikai.game.common.msg.pb.DeskUniqPB.internal_static_common_DeskUniq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kuaikai.game.common.msg.pb.DeskUniqPB.internal_static_common_DeskUniq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq.class, com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq.Builder.class);
    }

    public static com.google.protobuf.Parser<DeskUniq> PARSER =
        new com.google.protobuf.AbstractParser<DeskUniq>() {
      public DeskUniq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeskUniq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeskUniq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 deskId = 1;
    public static final int DESKID_FIELD_NUMBER = 1;
    private long deskId_;
    /**
     * <code>required int64 deskId = 1;</code>
     */
    public boolean hasDeskId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 deskId = 1;</code>
     */
    public long getDeskId() {
      return deskId_;
    }

    // optional int32 clubId = 2;
    public static final int CLUBID_FIELD_NUMBER = 2;
    private int clubId_;
    /**
     * <code>optional int32 clubId = 2;</code>
     */
    public boolean hasClubId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 clubId = 2;</code>
     */
    public int getClubId() {
      return clubId_;
    }

    private void initFields() {
      deskId_ = 0L;
      clubId_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDeskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, deskId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, clubId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, deskId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, clubId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.DeskUniq}
     *
     * <pre>
     * 牌桌唯一标识
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kuaikai.game.common.msg.pb.DeskUniqPB.internal_static_common_DeskUniq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kuaikai.game.common.msg.pb.DeskUniqPB.internal_static_common_DeskUniq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq.class, com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq.Builder.class);
      }

      // Construct using com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deskId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        clubId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kuaikai.game.common.msg.pb.DeskUniqPB.internal_static_common_DeskUniq_descriptor;
      }

      public com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq getDefaultInstanceForType() {
        return com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq.getDefaultInstance();
      }

      public com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq build() {
        com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq buildPartial() {
        com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq result = new com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deskId_ = deskId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.clubId_ = clubId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq) {
          return mergeFrom((com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq other) {
        if (other == com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq.getDefaultInstance()) return this;
        if (other.hasDeskId()) {
          setDeskId(other.getDeskId());
        }
        if (other.hasClubId()) {
          setClubId(other.getClubId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeskId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kuaikai.game.common.msg.pb.DeskUniqPB.DeskUniq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 deskId = 1;
      private long deskId_ ;
      /**
       * <code>required int64 deskId = 1;</code>
       */
      public boolean hasDeskId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 deskId = 1;</code>
       */
      public long getDeskId() {
        return deskId_;
      }
      /**
       * <code>required int64 deskId = 1;</code>
       */
      public Builder setDeskId(long value) {
        bitField0_ |= 0x00000001;
        deskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 deskId = 1;</code>
       */
      public Builder clearDeskId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deskId_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 clubId = 2;
      private int clubId_ ;
      /**
       * <code>optional int32 clubId = 2;</code>
       */
      public boolean hasClubId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 clubId = 2;</code>
       */
      public int getClubId() {
        return clubId_;
      }
      /**
       * <code>optional int32 clubId = 2;</code>
       */
      public Builder setClubId(int value) {
        bitField0_ |= 0x00000002;
        clubId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 clubId = 2;</code>
       */
      public Builder clearClubId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        clubId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:common.DeskUniq)
    }

    static {
      defaultInstance = new DeskUniq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common.DeskUniq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_DeskUniq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_DeskUniq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025common/DeskUniq.proto\022\006common\"*\n\010DeskU" +
      "niq\022\016\n\006deskId\030\001 \002(\003\022\016\n\006clubId\030\002 \001(\005B,\n\036c" +
      "om.kuaikai.game.common.msg.pbB\nDeskUniqP" +
      "B"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_common_DeskUniq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_common_DeskUniq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_common_DeskUniq_descriptor,
              new java.lang.String[] { "DeskId", "ClubId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
