// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/GlobalSetting.proto

package com.kuaikai.game.common.msg.pb;

public final class GlobalSettingPB {
  private GlobalSettingPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GlobalSettingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 volumeBg = 1;
    /**
     * <code>optional int32 volumeBg = 1;</code>
     *
     * <pre>
     * 通用设置
     * </pre>
     */
    boolean hasVolumeBg();
    /**
     * <code>optional int32 volumeBg = 1;</code>
     *
     * <pre>
     * 通用设置
     * </pre>
     */
    int getVolumeBg();

    // optional int32 volumePlay = 2;
    /**
     * <code>optional int32 volumePlay = 2;</code>
     *
     * <pre>
     * 打牌音效音量
     * </pre>
     */
    boolean hasVolumePlay();
    /**
     * <code>optional int32 volumePlay = 2;</code>
     *
     * <pre>
     * 打牌音效音量
     * </pre>
     */
    int getVolumePlay();

    // optional .common.Dialect dialect = 3;
    /**
     * <code>optional .common.Dialect dialect = 3;</code>
     *
     * <pre>
     * 方言
     * </pre>
     */
    boolean hasDialect();
    /**
     * <code>optional .common.Dialect dialect = 3;</code>
     *
     * <pre>
     * 方言
     * </pre>
     */
    com.kuaikai.game.common.msg.pb.DialectPB.Dialect getDialect();

    // optional .common.MahjongTheme mahjongTheme = 11;
    /**
     * <code>optional .common.MahjongTheme mahjongTheme = 11;</code>
     *
     * <pre>
     * 麻将相关
     * </pre>
     */
    boolean hasMahjongTheme();
    /**
     * <code>optional .common.MahjongTheme mahjongTheme = 11;</code>
     *
     * <pre>
     * 麻将相关
     * </pre>
     */
    com.kuaikai.game.common.msg.pb.MahjongThemePB.MahjongTheme getMahjongTheme();
  }
  /**
   * Protobuf type {@code common.GlobalSetting}
   *
   * <pre>
   * 全局设置
   * </pre>
   */
  public static final class GlobalSetting extends
      com.google.protobuf.GeneratedMessage
      implements GlobalSettingOrBuilder {
    // Use GlobalSetting.newBuilder() to construct.
    private GlobalSetting(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GlobalSetting(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GlobalSetting defaultInstance;
    public static GlobalSetting getDefaultInstance() {
      return defaultInstance;
    }

    public GlobalSetting getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GlobalSetting(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              volumeBg_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              volumePlay_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.kuaikai.game.common.msg.pb.DialectPB.Dialect value = com.kuaikai.game.common.msg.pb.DialectPB.Dialect.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                dialect_ = value;
              }
              break;
            }
            case 88: {
              int rawValue = input.readEnum();
              com.kuaikai.game.common.msg.pb.MahjongThemePB.MahjongTheme value = com.kuaikai.game.common.msg.pb.MahjongThemePB.MahjongTheme.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(11, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                mahjongTheme_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kuaikai.game.common.msg.pb.GlobalSettingPB.internal_static_common_GlobalSetting_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kuaikai.game.common.msg.pb.GlobalSettingPB.internal_static_common_GlobalSetting_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting.class, com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting.Builder.class);
    }

    public static com.google.protobuf.Parser<GlobalSetting> PARSER =
        new com.google.protobuf.AbstractParser<GlobalSetting>() {
      public GlobalSetting parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GlobalSetting(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GlobalSetting> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 volumeBg = 1;
    public static final int VOLUMEBG_FIELD_NUMBER = 1;
    private int volumeBg_;
    /**
     * <code>optional int32 volumeBg = 1;</code>
     *
     * <pre>
     * 通用设置
     * </pre>
     */
    public boolean hasVolumeBg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 volumeBg = 1;</code>
     *
     * <pre>
     * 通用设置
     * </pre>
     */
    public int getVolumeBg() {
      return volumeBg_;
    }

    // optional int32 volumePlay = 2;
    public static final int VOLUMEPLAY_FIELD_NUMBER = 2;
    private int volumePlay_;
    /**
     * <code>optional int32 volumePlay = 2;</code>
     *
     * <pre>
     * 打牌音效音量
     * </pre>
     */
    public boolean hasVolumePlay() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 volumePlay = 2;</code>
     *
     * <pre>
     * 打牌音效音量
     * </pre>
     */
    public int getVolumePlay() {
      return volumePlay_;
    }

    // optional .common.Dialect dialect = 3;
    public static final int DIALECT_FIELD_NUMBER = 3;
    private com.kuaikai.game.common.msg.pb.DialectPB.Dialect dialect_;
    /**
     * <code>optional .common.Dialect dialect = 3;</code>
     *
     * <pre>
     * 方言
     * </pre>
     */
    public boolean hasDialect() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .common.Dialect dialect = 3;</code>
     *
     * <pre>
     * 方言
     * </pre>
     */
    public com.kuaikai.game.common.msg.pb.DialectPB.Dialect getDialect() {
      return dialect_;
    }

    // optional .common.MahjongTheme mahjongTheme = 11;
    public static final int MAHJONGTHEME_FIELD_NUMBER = 11;
    private com.kuaikai.game.common.msg.pb.MahjongThemePB.MahjongTheme mahjongTheme_;
    /**
     * <code>optional .common.MahjongTheme mahjongTheme = 11;</code>
     *
     * <pre>
     * 麻将相关
     * </pre>
     */
    public boolean hasMahjongTheme() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .common.MahjongTheme mahjongTheme = 11;</code>
     *
     * <pre>
     * 麻将相关
     * </pre>
     */
    public com.kuaikai.game.common.msg.pb.MahjongThemePB.MahjongTheme getMahjongTheme() {
      return mahjongTheme_;
    }

    private void initFields() {
      volumeBg_ = 0;
      volumePlay_ = 0;
      dialect_ = com.kuaikai.game.common.msg.pb.DialectPB.Dialect.XIA_PU;
      mahjongTheme_ = com.kuaikai.game.common.msg.pb.MahjongThemePB.MahjongTheme.GREEN;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, volumeBg_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, volumePlay_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, dialect_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(11, mahjongTheme_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, volumeBg_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, volumePlay_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, dialect_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, mahjongTheme_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.GlobalSetting}
     *
     * <pre>
     * 全局设置
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSettingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kuaikai.game.common.msg.pb.GlobalSettingPB.internal_static_common_GlobalSetting_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kuaikai.game.common.msg.pb.GlobalSettingPB.internal_static_common_GlobalSetting_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting.class, com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting.Builder.class);
      }

      // Construct using com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        volumeBg_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        volumePlay_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        dialect_ = com.kuaikai.game.common.msg.pb.DialectPB.Dialect.XIA_PU;
        bitField0_ = (bitField0_ & ~0x00000004);
        mahjongTheme_ = com.kuaikai.game.common.msg.pb.MahjongThemePB.MahjongTheme.GREEN;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kuaikai.game.common.msg.pb.GlobalSettingPB.internal_static_common_GlobalSetting_descriptor;
      }

      public com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting getDefaultInstanceForType() {
        return com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting.getDefaultInstance();
      }

      public com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting build() {
        com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting buildPartial() {
        com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting result = new com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.volumeBg_ = volumeBg_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.volumePlay_ = volumePlay_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dialect_ = dialect_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.mahjongTheme_ = mahjongTheme_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting) {
          return mergeFrom((com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting other) {
        if (other == com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting.getDefaultInstance()) return this;
        if (other.hasVolumeBg()) {
          setVolumeBg(other.getVolumeBg());
        }
        if (other.hasVolumePlay()) {
          setVolumePlay(other.getVolumePlay());
        }
        if (other.hasDialect()) {
          setDialect(other.getDialect());
        }
        if (other.hasMahjongTheme()) {
          setMahjongTheme(other.getMahjongTheme());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kuaikai.game.common.msg.pb.GlobalSettingPB.GlobalSetting) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 volumeBg = 1;
      private int volumeBg_ ;
      /**
       * <code>optional int32 volumeBg = 1;</code>
       *
       * <pre>
       * 通用设置
       * </pre>
       */
      public boolean hasVolumeBg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 volumeBg = 1;</code>
       *
       * <pre>
       * 通用设置
       * </pre>
       */
      public int getVolumeBg() {
        return volumeBg_;
      }
      /**
       * <code>optional int32 volumeBg = 1;</code>
       *
       * <pre>
       * 通用设置
       * </pre>
       */
      public Builder setVolumeBg(int value) {
        bitField0_ |= 0x00000001;
        volumeBg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 volumeBg = 1;</code>
       *
       * <pre>
       * 通用设置
       * </pre>
       */
      public Builder clearVolumeBg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        volumeBg_ = 0;
        onChanged();
        return this;
      }

      // optional int32 volumePlay = 2;
      private int volumePlay_ ;
      /**
       * <code>optional int32 volumePlay = 2;</code>
       *
       * <pre>
       * 打牌音效音量
       * </pre>
       */
      public boolean hasVolumePlay() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 volumePlay = 2;</code>
       *
       * <pre>
       * 打牌音效音量
       * </pre>
       */
      public int getVolumePlay() {
        return volumePlay_;
      }
      /**
       * <code>optional int32 volumePlay = 2;</code>
       *
       * <pre>
       * 打牌音效音量
       * </pre>
       */
      public Builder setVolumePlay(int value) {
        bitField0_ |= 0x00000002;
        volumePlay_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 volumePlay = 2;</code>
       *
       * <pre>
       * 打牌音效音量
       * </pre>
       */
      public Builder clearVolumePlay() {
        bitField0_ = (bitField0_ & ~0x00000002);
        volumePlay_ = 0;
        onChanged();
        return this;
      }

      // optional .common.Dialect dialect = 3;
      private com.kuaikai.game.common.msg.pb.DialectPB.Dialect dialect_ = com.kuaikai.game.common.msg.pb.DialectPB.Dialect.XIA_PU;
      /**
       * <code>optional .common.Dialect dialect = 3;</code>
       *
       * <pre>
       * 方言
       * </pre>
       */
      public boolean hasDialect() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .common.Dialect dialect = 3;</code>
       *
       * <pre>
       * 方言
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.DialectPB.Dialect getDialect() {
        return dialect_;
      }
      /**
       * <code>optional .common.Dialect dialect = 3;</code>
       *
       * <pre>
       * 方言
       * </pre>
       */
      public Builder setDialect(com.kuaikai.game.common.msg.pb.DialectPB.Dialect value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        dialect_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .common.Dialect dialect = 3;</code>
       *
       * <pre>
       * 方言
       * </pre>
       */
      public Builder clearDialect() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dialect_ = com.kuaikai.game.common.msg.pb.DialectPB.Dialect.XIA_PU;
        onChanged();
        return this;
      }

      // optional .common.MahjongTheme mahjongTheme = 11;
      private com.kuaikai.game.common.msg.pb.MahjongThemePB.MahjongTheme mahjongTheme_ = com.kuaikai.game.common.msg.pb.MahjongThemePB.MahjongTheme.GREEN;
      /**
       * <code>optional .common.MahjongTheme mahjongTheme = 11;</code>
       *
       * <pre>
       * 麻将相关
       * </pre>
       */
      public boolean hasMahjongTheme() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .common.MahjongTheme mahjongTheme = 11;</code>
       *
       * <pre>
       * 麻将相关
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.MahjongThemePB.MahjongTheme getMahjongTheme() {
        return mahjongTheme_;
      }
      /**
       * <code>optional .common.MahjongTheme mahjongTheme = 11;</code>
       *
       * <pre>
       * 麻将相关
       * </pre>
       */
      public Builder setMahjongTheme(com.kuaikai.game.common.msg.pb.MahjongThemePB.MahjongTheme value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        mahjongTheme_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .common.MahjongTheme mahjongTheme = 11;</code>
       *
       * <pre>
       * 麻将相关
       * </pre>
       */
      public Builder clearMahjongTheme() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mahjongTheme_ = com.kuaikai.game.common.msg.pb.MahjongThemePB.MahjongTheme.GREEN;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:common.GlobalSetting)
    }

    static {
      defaultInstance = new GlobalSetting(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:common.GlobalSetting)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_GlobalSetting_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_GlobalSetting_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032common/GlobalSetting.proto\022\006common\032\024co" +
      "mmon/Dialect.proto\032\031common/MahjongTheme." +
      "proto\"\203\001\n\rGlobalSetting\022\020\n\010volumeBg\030\001 \001(" +
      "\005\022\022\n\nvolumePlay\030\002 \001(\005\022 \n\007dialect\030\003 \001(\0162\017" +
      ".common.Dialect\022*\n\014mahjongTheme\030\013 \001(\0162\024." +
      "common.MahjongThemeB1\n\036com.kuaikai.game." +
      "common.msg.pbB\017GlobalSettingPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_common_GlobalSetting_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_common_GlobalSetting_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_common_GlobalSetting_descriptor,
              new java.lang.String[] { "VolumeBg", "VolumePlay", "Dialect", "MahjongTheme", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kuaikai.game.common.msg.pb.DialectPB.getDescriptor(),
          com.kuaikai.game.common.msg.pb.MahjongThemePB.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
