// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/SLogout.proto

package com.kuaikai.game.common.msg.pb;

public final class SLogoutPB {
  private SLogoutPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SLogoutOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .account.SLogout.ReturnCode returnCode = 1;
    /**
     * <code>required .account.SLogout.ReturnCode returnCode = 1;</code>
     */
    boolean hasReturnCode();
    /**
     * <code>required .account.SLogout.ReturnCode returnCode = 1;</code>
     */
    com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.ReturnCode getReturnCode();
  }
  /**
   * Protobuf type {@code account.SLogout}
   */
  public static final class SLogout extends
      com.google.protobuf.GeneratedMessage
      implements SLogoutOrBuilder {
    // Use SLogout.newBuilder() to construct.
    private SLogout(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SLogout(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SLogout defaultInstance;
    public static SLogout getDefaultInstance() {
      return defaultInstance;
    }

    public SLogout getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SLogout(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.ReturnCode value = com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.ReturnCode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                returnCode_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kuaikai.game.common.msg.pb.SLogoutPB.internal_static_account_SLogout_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kuaikai.game.common.msg.pb.SLogoutPB.internal_static_account_SLogout_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.class, com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.Builder.class);
    }

    public static com.google.protobuf.Parser<SLogout> PARSER =
        new com.google.protobuf.AbstractParser<SLogout>() {
      public SLogout parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SLogout(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SLogout> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code account.SLogout.ReturnCode}
     */
    public enum ReturnCode
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SUCCESS = 0;</code>
       */
      SUCCESS(0, 0),
      /**
       * <code>ALREADY_LOGOUT = 1;</code>
       */
      ALREADY_LOGOUT(1, 1),
      ;

      /**
       * <code>SUCCESS = 0;</code>
       */
      public static final int SUCCESS_VALUE = 0;
      /**
       * <code>ALREADY_LOGOUT = 1;</code>
       */
      public static final int ALREADY_LOGOUT_VALUE = 1;


      public final int getNumber() { return value; }

      public static ReturnCode valueOf(int value) {
        switch (value) {
          case 0: return SUCCESS;
          case 1: return ALREADY_LOGOUT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ReturnCode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ReturnCode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ReturnCode>() {
              public ReturnCode findValueByNumber(int number) {
                return ReturnCode.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.getDescriptor().getEnumTypes().get(0);
      }

      private static final ReturnCode[] VALUES = values();

      public static ReturnCode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ReturnCode(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:account.SLogout.ReturnCode)
    }

    private int bitField0_;
    // required .account.SLogout.ReturnCode returnCode = 1;
    public static final int RETURNCODE_FIELD_NUMBER = 1;
    private com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.ReturnCode returnCode_;
    /**
     * <code>required .account.SLogout.ReturnCode returnCode = 1;</code>
     */
    public boolean hasReturnCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .account.SLogout.ReturnCode returnCode = 1;</code>
     */
    public com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.ReturnCode getReturnCode() {
      return returnCode_;
    }

    private void initFields() {
      returnCode_ = com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.ReturnCode.SUCCESS;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasReturnCode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, returnCode_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, returnCode_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code account.SLogout}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kuaikai.game.common.msg.pb.SLogoutPB.SLogoutOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kuaikai.game.common.msg.pb.SLogoutPB.internal_static_account_SLogout_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kuaikai.game.common.msg.pb.SLogoutPB.internal_static_account_SLogout_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.class, com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.Builder.class);
      }

      // Construct using com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        returnCode_ = com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.ReturnCode.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kuaikai.game.common.msg.pb.SLogoutPB.internal_static_account_SLogout_descriptor;
      }

      public com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout getDefaultInstanceForType() {
        return com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.getDefaultInstance();
      }

      public com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout build() {
        com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout buildPartial() {
        com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout result = new com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.returnCode_ = returnCode_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout) {
          return mergeFrom((com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout other) {
        if (other == com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.getDefaultInstance()) return this;
        if (other.hasReturnCode()) {
          setReturnCode(other.getReturnCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasReturnCode()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .account.SLogout.ReturnCode returnCode = 1;
      private com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.ReturnCode returnCode_ = com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.ReturnCode.SUCCESS;
      /**
       * <code>required .account.SLogout.ReturnCode returnCode = 1;</code>
       */
      public boolean hasReturnCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .account.SLogout.ReturnCode returnCode = 1;</code>
       */
      public com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.ReturnCode getReturnCode() {
        return returnCode_;
      }
      /**
       * <code>required .account.SLogout.ReturnCode returnCode = 1;</code>
       */
      public Builder setReturnCode(com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.ReturnCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        returnCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .account.SLogout.ReturnCode returnCode = 1;</code>
       */
      public Builder clearReturnCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        returnCode_ = com.kuaikai.game.common.msg.pb.SLogoutPB.SLogout.ReturnCode.SUCCESS;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:account.SLogout)
    }

    static {
      defaultInstance = new SLogout(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:account.SLogout)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_account_SLogout_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_SLogout_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025account/SLogout.proto\022\007account\"i\n\007SLog" +
      "out\022/\n\nreturnCode\030\001 \002(\0162\033.account.SLogou" +
      "t.ReturnCode\"-\n\nReturnCode\022\013\n\007SUCCESS\020\000\022" +
      "\022\n\016ALREADY_LOGOUT\020\001B+\n\036com.kuaikai.game." +
      "common.msg.pbB\tSLogoutPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_account_SLogout_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_account_SLogout_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_account_SLogout_descriptor,
              new java.lang.String[] { "ReturnCode", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
