// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hall/SDeskInfo.proto

package com.kuaikai.game.hall.msg.pb;

public final class SDeskInfoPB {
  private SDeskInfoPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SDeskInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .common.DeskInfo desk = 1;
    /**
     * <code>required .common.DeskInfo desk = 1;</code>
     *
     * <pre>
     * 牌桌信息
     * </pre>
     */
    boolean hasDesk();
    /**
     * <code>required .common.DeskInfo desk = 1;</code>
     *
     * <pre>
     * 牌桌信息
     * </pre>
     */
    com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo getDesk();
    /**
     * <code>required .common.DeskInfo desk = 1;</code>
     *
     * <pre>
     * 牌桌信息
     * </pre>
     */
    com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfoOrBuilder getDeskOrBuilder();
  }
  /**
   * Protobuf type {@code hall.SDeskInfo}
   *
   * <pre>
   * 大厅牌桌信息
   * </pre>
   */
  public static final class SDeskInfo extends
      com.google.protobuf.GeneratedMessage
      implements SDeskInfoOrBuilder {
    // Use SDeskInfo.newBuilder() to construct.
    private SDeskInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SDeskInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SDeskInfo defaultInstance;
    public static SDeskInfo getDefaultInstance() {
      return defaultInstance;
    }

    public SDeskInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SDeskInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = desk_.toBuilder();
              }
              desk_ = input.readMessage(com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(desk_);
                desk_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kuaikai.game.hall.msg.pb.SDeskInfoPB.internal_static_hall_SDeskInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kuaikai.game.hall.msg.pb.SDeskInfoPB.internal_static_hall_SDeskInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo.class, com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<SDeskInfo> PARSER =
        new com.google.protobuf.AbstractParser<SDeskInfo>() {
      public SDeskInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SDeskInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SDeskInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .common.DeskInfo desk = 1;
    public static final int DESK_FIELD_NUMBER = 1;
    private com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo desk_;
    /**
     * <code>required .common.DeskInfo desk = 1;</code>
     *
     * <pre>
     * 牌桌信息
     * </pre>
     */
    public boolean hasDesk() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .common.DeskInfo desk = 1;</code>
     *
     * <pre>
     * 牌桌信息
     * </pre>
     */
    public com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo getDesk() {
      return desk_;
    }
    /**
     * <code>required .common.DeskInfo desk = 1;</code>
     *
     * <pre>
     * 牌桌信息
     * </pre>
     */
    public com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfoOrBuilder getDeskOrBuilder() {
      return desk_;
    }

    private void initFields() {
      desk_ = com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasDesk()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getDesk().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, desk_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, desk_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hall.SDeskInfo}
     *
     * <pre>
     * 大厅牌桌信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kuaikai.game.hall.msg.pb.SDeskInfoPB.internal_static_hall_SDeskInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kuaikai.game.hall.msg.pb.SDeskInfoPB.internal_static_hall_SDeskInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo.class, com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo.Builder.class);
      }

      // Construct using com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDeskFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (deskBuilder_ == null) {
          desk_ = com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.getDefaultInstance();
        } else {
          deskBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kuaikai.game.hall.msg.pb.SDeskInfoPB.internal_static_hall_SDeskInfo_descriptor;
      }

      public com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo getDefaultInstanceForType() {
        return com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo.getDefaultInstance();
      }

      public com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo build() {
        com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo buildPartial() {
        com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo result = new com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (deskBuilder_ == null) {
          result.desk_ = desk_;
        } else {
          result.desk_ = deskBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo) {
          return mergeFrom((com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo other) {
        if (other == com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo.getDefaultInstance()) return this;
        if (other.hasDesk()) {
          mergeDesk(other.getDesk());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDesk()) {
          
          return false;
        }
        if (!getDesk().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kuaikai.game.hall.msg.pb.SDeskInfoPB.SDeskInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .common.DeskInfo desk = 1;
      private com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo desk_ = com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo, com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.Builder, com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfoOrBuilder> deskBuilder_;
      /**
       * <code>required .common.DeskInfo desk = 1;</code>
       *
       * <pre>
       * 牌桌信息
       * </pre>
       */
      public boolean hasDesk() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .common.DeskInfo desk = 1;</code>
       *
       * <pre>
       * 牌桌信息
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo getDesk() {
        if (deskBuilder_ == null) {
          return desk_;
        } else {
          return deskBuilder_.getMessage();
        }
      }
      /**
       * <code>required .common.DeskInfo desk = 1;</code>
       *
       * <pre>
       * 牌桌信息
       * </pre>
       */
      public Builder setDesk(com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo value) {
        if (deskBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          desk_ = value;
          onChanged();
        } else {
          deskBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .common.DeskInfo desk = 1;</code>
       *
       * <pre>
       * 牌桌信息
       * </pre>
       */
      public Builder setDesk(
          com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.Builder builderForValue) {
        if (deskBuilder_ == null) {
          desk_ = builderForValue.build();
          onChanged();
        } else {
          deskBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .common.DeskInfo desk = 1;</code>
       *
       * <pre>
       * 牌桌信息
       * </pre>
       */
      public Builder mergeDesk(com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo value) {
        if (deskBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              desk_ != com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.getDefaultInstance()) {
            desk_ =
              com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.newBuilder(desk_).mergeFrom(value).buildPartial();
          } else {
            desk_ = value;
          }
          onChanged();
        } else {
          deskBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .common.DeskInfo desk = 1;</code>
       *
       * <pre>
       * 牌桌信息
       * </pre>
       */
      public Builder clearDesk() {
        if (deskBuilder_ == null) {
          desk_ = com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.getDefaultInstance();
          onChanged();
        } else {
          deskBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .common.DeskInfo desk = 1;</code>
       *
       * <pre>
       * 牌桌信息
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.Builder getDeskBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDeskFieldBuilder().getBuilder();
      }
      /**
       * <code>required .common.DeskInfo desk = 1;</code>
       *
       * <pre>
       * 牌桌信息
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfoOrBuilder getDeskOrBuilder() {
        if (deskBuilder_ != null) {
          return deskBuilder_.getMessageOrBuilder();
        } else {
          return desk_;
        }
      }
      /**
       * <code>required .common.DeskInfo desk = 1;</code>
       *
       * <pre>
       * 牌桌信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo, com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.Builder, com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfoOrBuilder> 
          getDeskFieldBuilder() {
        if (deskBuilder_ == null) {
          deskBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo, com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfo.Builder, com.kuaikai.game.common.msg.pb.DeskInfoPB.DeskInfoOrBuilder>(
                  desk_,
                  getParentForChildren(),
                  isClean());
          desk_ = null;
        }
        return deskBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:hall.SDeskInfo)
    }

    static {
      defaultInstance = new SDeskInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:hall.SDeskInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hall_SDeskInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hall_SDeskInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024hall/SDeskInfo.proto\022\004hall\032\025common/Des" +
      "kInfo.proto\"+\n\tSDeskInfo\022\036\n\004desk\030\001 \002(\0132\020" +
      ".common.DeskInfoB+\n\034com.kuaikai.game.hal" +
      "l.msg.pbB\013SDeskInfoPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_hall_SDeskInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_hall_SDeskInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_hall_SDeskInfo_descriptor,
              new java.lang.String[] { "Desk", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kuaikai.game.common.msg.pb.DeskInfoPB.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
