// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mahjong/PlayerInfo.proto

package com.kuaikai.game.mahjong.msg.pb;

public final class PlayerInfoPB {
  private PlayerInfoPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PlayerInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .PlayerBasicInfo basicInfo = 1;
    /**
     * <code>required .PlayerBasicInfo basicInfo = 1;</code>
     *
     * <pre>
     * 玩家基本信息
     * </pre>
     */
    boolean hasBasicInfo();
    /**
     * <code>required .PlayerBasicInfo basicInfo = 1;</code>
     *
     * <pre>
     * 玩家基本信息
     * </pre>
     */
    com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo getBasicInfo();
    /**
     * <code>required .PlayerBasicInfo basicInfo = 1;</code>
     *
     * <pre>
     * 玩家基本信息
     * </pre>
     */
    com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfoOrBuilder getBasicInfoOrBuilder();

    // required bool prepared = 2;
    /**
     * <code>required bool prepared = 2;</code>
     *
     * <pre>
     * 是否准备
     * </pre>
     */
    boolean hasPrepared();
    /**
     * <code>required bool prepared = 2;</code>
     *
     * <pre>
     * 是否准备
     * </pre>
     */
    boolean getPrepared();

    // required bool offline = 3;
    /**
     * <code>required bool offline = 3;</code>
     *
     * <pre>
     * 是否离线
     * </pre>
     */
    boolean hasOffline();
    /**
     * <code>required bool offline = 3;</code>
     *
     * <pre>
     * 是否离线
     * </pre>
     */
    boolean getOffline();

    // repeated int32 points = 4;
    /**
     * <code>repeated int32 points = 4;</code>
     *
     * <pre>
     * 各项分数
     * </pre>
     */
    java.util.List<java.lang.Integer> getPointsList();
    /**
     * <code>repeated int32 points = 4;</code>
     *
     * <pre>
     * 各项分数
     * </pre>
     */
    int getPointsCount();
    /**
     * <code>repeated int32 points = 4;</code>
     *
     * <pre>
     * 各项分数
     * </pre>
     */
    int getPoints(int index);

    // repeated int32 diPoints = 5;
    /**
     * <code>repeated int32 diPoints = 5;</code>
     *
     * <pre>
     * 当前底各项分数
     * </pre>
     */
    java.util.List<java.lang.Integer> getDiPointsList();
    /**
     * <code>repeated int32 diPoints = 5;</code>
     *
     * <pre>
     * 当前底各项分数
     * </pre>
     */
    int getDiPointsCount();
    /**
     * <code>repeated int32 diPoints = 5;</code>
     *
     * <pre>
     * 当前底各项分数
     * </pre>
     */
    int getDiPoints(int index);
  }
  /**
   * Protobuf type {@code PlayerInfo}
   */
  public static final class PlayerInfo extends
      com.google.protobuf.GeneratedMessage
      implements PlayerInfoOrBuilder {
    // Use PlayerInfo.newBuilder() to construct.
    private PlayerInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PlayerInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PlayerInfo defaultInstance;
    public static PlayerInfo getDefaultInstance() {
      return defaultInstance;
    }

    public PlayerInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = basicInfo_.toBuilder();
              }
              basicInfo_ = input.readMessage(com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(basicInfo_);
                basicInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              prepared_ = input.readBool();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              offline_ = input.readBool();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                points_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              points_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                points_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                points_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                diPoints_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              diPoints_.add(input.readInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                diPoints_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                diPoints_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          points_ = java.util.Collections.unmodifiableList(points_);
        }
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          diPoints_ = java.util.Collections.unmodifiableList(diPoints_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.internal_static_PlayerInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.internal_static_PlayerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo.class, com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<PlayerInfo> PARSER =
        new com.google.protobuf.AbstractParser<PlayerInfo>() {
      public PlayerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .PlayerBasicInfo basicInfo = 1;
    public static final int BASICINFO_FIELD_NUMBER = 1;
    private com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo basicInfo_;
    /**
     * <code>required .PlayerBasicInfo basicInfo = 1;</code>
     *
     * <pre>
     * 玩家基本信息
     * </pre>
     */
    public boolean hasBasicInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .PlayerBasicInfo basicInfo = 1;</code>
     *
     * <pre>
     * 玩家基本信息
     * </pre>
     */
    public com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo getBasicInfo() {
      return basicInfo_;
    }
    /**
     * <code>required .PlayerBasicInfo basicInfo = 1;</code>
     *
     * <pre>
     * 玩家基本信息
     * </pre>
     */
    public com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfoOrBuilder getBasicInfoOrBuilder() {
      return basicInfo_;
    }

    // required bool prepared = 2;
    public static final int PREPARED_FIELD_NUMBER = 2;
    private boolean prepared_;
    /**
     * <code>required bool prepared = 2;</code>
     *
     * <pre>
     * 是否准备
     * </pre>
     */
    public boolean hasPrepared() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool prepared = 2;</code>
     *
     * <pre>
     * 是否准备
     * </pre>
     */
    public boolean getPrepared() {
      return prepared_;
    }

    // required bool offline = 3;
    public static final int OFFLINE_FIELD_NUMBER = 3;
    private boolean offline_;
    /**
     * <code>required bool offline = 3;</code>
     *
     * <pre>
     * 是否离线
     * </pre>
     */
    public boolean hasOffline() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bool offline = 3;</code>
     *
     * <pre>
     * 是否离线
     * </pre>
     */
    public boolean getOffline() {
      return offline_;
    }

    // repeated int32 points = 4;
    public static final int POINTS_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> points_;
    /**
     * <code>repeated int32 points = 4;</code>
     *
     * <pre>
     * 各项分数
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getPointsList() {
      return points_;
    }
    /**
     * <code>repeated int32 points = 4;</code>
     *
     * <pre>
     * 各项分数
     * </pre>
     */
    public int getPointsCount() {
      return points_.size();
    }
    /**
     * <code>repeated int32 points = 4;</code>
     *
     * <pre>
     * 各项分数
     * </pre>
     */
    public int getPoints(int index) {
      return points_.get(index);
    }

    // repeated int32 diPoints = 5;
    public static final int DIPOINTS_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> diPoints_;
    /**
     * <code>repeated int32 diPoints = 5;</code>
     *
     * <pre>
     * 当前底各项分数
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getDiPointsList() {
      return diPoints_;
    }
    /**
     * <code>repeated int32 diPoints = 5;</code>
     *
     * <pre>
     * 当前底各项分数
     * </pre>
     */
    public int getDiPointsCount() {
      return diPoints_.size();
    }
    /**
     * <code>repeated int32 diPoints = 5;</code>
     *
     * <pre>
     * 当前底各项分数
     * </pre>
     */
    public int getDiPoints(int index) {
      return diPoints_.get(index);
    }

    private void initFields() {
      basicInfo_ = com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo.getDefaultInstance();
      prepared_ = false;
      offline_ = false;
      points_ = java.util.Collections.emptyList();
      diPoints_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBasicInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrepared()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOffline()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getBasicInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, basicInfo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, prepared_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, offline_);
      }
      for (int i = 0; i < points_.size(); i++) {
        output.writeInt32(4, points_.get(i));
      }
      for (int i = 0; i < diPoints_.size(); i++) {
        output.writeInt32(5, diPoints_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, basicInfo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, prepared_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, offline_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < points_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(points_.get(i));
        }
        size += dataSize;
        size += 1 * getPointsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < diPoints_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(diPoints_.get(i));
        }
        size += dataSize;
        size += 1 * getDiPointsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.internal_static_PlayerInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.internal_static_PlayerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo.class, com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo.Builder.class);
      }

      // Construct using com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBasicInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (basicInfoBuilder_ == null) {
          basicInfo_ = com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo.getDefaultInstance();
        } else {
          basicInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        prepared_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        offline_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        points_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        diPoints_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.internal_static_PlayerInfo_descriptor;
      }

      public com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo getDefaultInstanceForType() {
        return com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo.getDefaultInstance();
      }

      public com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo build() {
        com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo buildPartial() {
        com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo result = new com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (basicInfoBuilder_ == null) {
          result.basicInfo_ = basicInfo_;
        } else {
          result.basicInfo_ = basicInfoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.prepared_ = prepared_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.offline_ = offline_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          points_ = java.util.Collections.unmodifiableList(points_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.points_ = points_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          diPoints_ = java.util.Collections.unmodifiableList(diPoints_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.diPoints_ = diPoints_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo) {
          return mergeFrom((com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo other) {
        if (other == com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo.getDefaultInstance()) return this;
        if (other.hasBasicInfo()) {
          mergeBasicInfo(other.getBasicInfo());
        }
        if (other.hasPrepared()) {
          setPrepared(other.getPrepared());
        }
        if (other.hasOffline()) {
          setOffline(other.getOffline());
        }
        if (!other.points_.isEmpty()) {
          if (points_.isEmpty()) {
            points_ = other.points_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePointsIsMutable();
            points_.addAll(other.points_);
          }
          onChanged();
        }
        if (!other.diPoints_.isEmpty()) {
          if (diPoints_.isEmpty()) {
            diPoints_ = other.diPoints_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureDiPointsIsMutable();
            diPoints_.addAll(other.diPoints_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBasicInfo()) {
          
          return false;
        }
        if (!hasPrepared()) {
          
          return false;
        }
        if (!hasOffline()) {
          
          return false;
        }
        if (!getBasicInfo().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.kuaikai.game.mahjong.msg.pb.PlayerInfoPB.PlayerInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .PlayerBasicInfo basicInfo = 1;
      private com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo basicInfo_ = com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo, com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo.Builder, com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfoOrBuilder> basicInfoBuilder_;
      /**
       * <code>required .PlayerBasicInfo basicInfo = 1;</code>
       *
       * <pre>
       * 玩家基本信息
       * </pre>
       */
      public boolean hasBasicInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .PlayerBasicInfo basicInfo = 1;</code>
       *
       * <pre>
       * 玩家基本信息
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo getBasicInfo() {
        if (basicInfoBuilder_ == null) {
          return basicInfo_;
        } else {
          return basicInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .PlayerBasicInfo basicInfo = 1;</code>
       *
       * <pre>
       * 玩家基本信息
       * </pre>
       */
      public Builder setBasicInfo(com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo value) {
        if (basicInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          basicInfo_ = value;
          onChanged();
        } else {
          basicInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PlayerBasicInfo basicInfo = 1;</code>
       *
       * <pre>
       * 玩家基本信息
       * </pre>
       */
      public Builder setBasicInfo(
          com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo.Builder builderForValue) {
        if (basicInfoBuilder_ == null) {
          basicInfo_ = builderForValue.build();
          onChanged();
        } else {
          basicInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PlayerBasicInfo basicInfo = 1;</code>
       *
       * <pre>
       * 玩家基本信息
       * </pre>
       */
      public Builder mergeBasicInfo(com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo value) {
        if (basicInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              basicInfo_ != com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo.getDefaultInstance()) {
            basicInfo_ =
              com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo.newBuilder(basicInfo_).mergeFrom(value).buildPartial();
          } else {
            basicInfo_ = value;
          }
          onChanged();
        } else {
          basicInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PlayerBasicInfo basicInfo = 1;</code>
       *
       * <pre>
       * 玩家基本信息
       * </pre>
       */
      public Builder clearBasicInfo() {
        if (basicInfoBuilder_ == null) {
          basicInfo_ = com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo.getDefaultInstance();
          onChanged();
        } else {
          basicInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .PlayerBasicInfo basicInfo = 1;</code>
       *
       * <pre>
       * 玩家基本信息
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo.Builder getBasicInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBasicInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .PlayerBasicInfo basicInfo = 1;</code>
       *
       * <pre>
       * 玩家基本信息
       * </pre>
       */
      public com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfoOrBuilder getBasicInfoOrBuilder() {
        if (basicInfoBuilder_ != null) {
          return basicInfoBuilder_.getMessageOrBuilder();
        } else {
          return basicInfo_;
        }
      }
      /**
       * <code>required .PlayerBasicInfo basicInfo = 1;</code>
       *
       * <pre>
       * 玩家基本信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo, com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo.Builder, com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfoOrBuilder> 
          getBasicInfoFieldBuilder() {
        if (basicInfoBuilder_ == null) {
          basicInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo, com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfo.Builder, com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.PlayerBasicInfoOrBuilder>(
                  basicInfo_,
                  getParentForChildren(),
                  isClean());
          basicInfo_ = null;
        }
        return basicInfoBuilder_;
      }

      // required bool prepared = 2;
      private boolean prepared_ ;
      /**
       * <code>required bool prepared = 2;</code>
       *
       * <pre>
       * 是否准备
       * </pre>
       */
      public boolean hasPrepared() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool prepared = 2;</code>
       *
       * <pre>
       * 是否准备
       * </pre>
       */
      public boolean getPrepared() {
        return prepared_;
      }
      /**
       * <code>required bool prepared = 2;</code>
       *
       * <pre>
       * 是否准备
       * </pre>
       */
      public Builder setPrepared(boolean value) {
        bitField0_ |= 0x00000002;
        prepared_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool prepared = 2;</code>
       *
       * <pre>
       * 是否准备
       * </pre>
       */
      public Builder clearPrepared() {
        bitField0_ = (bitField0_ & ~0x00000002);
        prepared_ = false;
        onChanged();
        return this;
      }

      // required bool offline = 3;
      private boolean offline_ ;
      /**
       * <code>required bool offline = 3;</code>
       *
       * <pre>
       * 是否离线
       * </pre>
       */
      public boolean hasOffline() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bool offline = 3;</code>
       *
       * <pre>
       * 是否离线
       * </pre>
       */
      public boolean getOffline() {
        return offline_;
      }
      /**
       * <code>required bool offline = 3;</code>
       *
       * <pre>
       * 是否离线
       * </pre>
       */
      public Builder setOffline(boolean value) {
        bitField0_ |= 0x00000004;
        offline_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool offline = 3;</code>
       *
       * <pre>
       * 是否离线
       * </pre>
       */
      public Builder clearOffline() {
        bitField0_ = (bitField0_ & ~0x00000004);
        offline_ = false;
        onChanged();
        return this;
      }

      // repeated int32 points = 4;
      private java.util.List<java.lang.Integer> points_ = java.util.Collections.emptyList();
      private void ensurePointsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          points_ = new java.util.ArrayList<java.lang.Integer>(points_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 points = 4;</code>
       *
       * <pre>
       * 各项分数
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getPointsList() {
        return java.util.Collections.unmodifiableList(points_);
      }
      /**
       * <code>repeated int32 points = 4;</code>
       *
       * <pre>
       * 各项分数
       * </pre>
       */
      public int getPointsCount() {
        return points_.size();
      }
      /**
       * <code>repeated int32 points = 4;</code>
       *
       * <pre>
       * 各项分数
       * </pre>
       */
      public int getPoints(int index) {
        return points_.get(index);
      }
      /**
       * <code>repeated int32 points = 4;</code>
       *
       * <pre>
       * 各项分数
       * </pre>
       */
      public Builder setPoints(
          int index, int value) {
        ensurePointsIsMutable();
        points_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 points = 4;</code>
       *
       * <pre>
       * 各项分数
       * </pre>
       */
      public Builder addPoints(int value) {
        ensurePointsIsMutable();
        points_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 points = 4;</code>
       *
       * <pre>
       * 各项分数
       * </pre>
       */
      public Builder addAllPoints(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensurePointsIsMutable();
        super.addAll(values, points_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 points = 4;</code>
       *
       * <pre>
       * 各项分数
       * </pre>
       */
      public Builder clearPoints() {
        points_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // repeated int32 diPoints = 5;
      private java.util.List<java.lang.Integer> diPoints_ = java.util.Collections.emptyList();
      private void ensureDiPointsIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          diPoints_ = new java.util.ArrayList<java.lang.Integer>(diPoints_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int32 diPoints = 5;</code>
       *
       * <pre>
       * 当前底各项分数
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getDiPointsList() {
        return java.util.Collections.unmodifiableList(diPoints_);
      }
      /**
       * <code>repeated int32 diPoints = 5;</code>
       *
       * <pre>
       * 当前底各项分数
       * </pre>
       */
      public int getDiPointsCount() {
        return diPoints_.size();
      }
      /**
       * <code>repeated int32 diPoints = 5;</code>
       *
       * <pre>
       * 当前底各项分数
       * </pre>
       */
      public int getDiPoints(int index) {
        return diPoints_.get(index);
      }
      /**
       * <code>repeated int32 diPoints = 5;</code>
       *
       * <pre>
       * 当前底各项分数
       * </pre>
       */
      public Builder setDiPoints(
          int index, int value) {
        ensureDiPointsIsMutable();
        diPoints_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 diPoints = 5;</code>
       *
       * <pre>
       * 当前底各项分数
       * </pre>
       */
      public Builder addDiPoints(int value) {
        ensureDiPointsIsMutable();
        diPoints_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 diPoints = 5;</code>
       *
       * <pre>
       * 当前底各项分数
       * </pre>
       */
      public Builder addAllDiPoints(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureDiPointsIsMutable();
        super.addAll(values, diPoints_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 diPoints = 5;</code>
       *
       * <pre>
       * 当前底各项分数
       * </pre>
       */
      public Builder clearDiPoints() {
        diPoints_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PlayerInfo)
    }

    static {
      defaultInstance = new PlayerInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PlayerInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PlayerInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030mahjong/PlayerInfo.proto\032\035account/Play" +
      "erBasicInfo.proto\"v\n\nPlayerInfo\022#\n\tbasic" +
      "Info\030\001 \002(\0132\020.PlayerBasicInfo\022\020\n\010prepared" +
      "\030\002 \002(\010\022\017\n\007offline\030\003 \002(\010\022\016\n\006points\030\004 \003(\005\022" +
      "\020\n\010diPoints\030\005 \003(\005B/\n\037com.kuaikai.game.ma" +
      "hjong.msg.pbB\014PlayerInfoPB"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_PlayerInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_PlayerInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_PlayerInfo_descriptor,
              new java.lang.String[] { "BasicInfo", "Prepared", "Offline", "Points", "DiPoints", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.kuaikai.game.common.msg.pb.PlayerBasicInfoPB.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
